-- MySQL Script generated by MySQL Workbench
-- Fri Sep 13 08:09:39 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema capacitacao
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema capacitacao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `capacitacao` DEFAULT CHARACTER SET utf8 ;
USE `capacitacao` ;

-- -----------------------------------------------------
-- Table `capacitação`.`Instrutor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capacitacao`.`Instrutor` (
  `idInstrutor`   INT(11) NOT NULL,
  `Nome`          VARCHAR(100) NOT NULL,
  `Email`         VARCHAR(100) NOT NULL,
  `Valor_Hora`    DOUBLE NOT NULL,
  `Certificados`  VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idInstrutor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `capacitação`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capacitacao`.`Curso` (
  `idCurso`       INT(11) NOT NULL,
  `Nome`          VARCHAR(100) NOT NULL,
  `Requisito`     VARCHAR(100) NOT NULL,
  `Carga_Horaria` DOUBLE NOT NULL,
  `Preco`         DOUBLE NOT NULL,
  PRIMARY KEY (`idCurso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `capacitação`.`Turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capacitacao`.`Turma` (
  `idTurma`        INT(11) NOT NULL,
  `Carga_Horaria`  DOUBLE NOT NULL,
  `Data_Inicial`   DATE NOT NULL,
  `Data_Final`     DATE NOT NULL,
  `Curso_idCurso`  INT(11) NOT NULL,
  `Instrutor_idInstrutor` INT(11) NOT NULL,
  PRIMARY KEY (`idTurma`),
 -- INDEX `fk_Turma_Curso1_idx` (`Curso_idCurso` ASC) VISIBLE,
  -- INDEX `fk_Turma_Instrutor1_idx` (`Instrutor_idInstrutor` ASC) VISIBLE,
  CONSTRAINT `fk_Turma_Curso1`
    FOREIGN KEY (`Curso_idCurso`)
    REFERENCES `capacitacao`.`Curso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Turma_Instrutor1`
    FOREIGN KEY (`Instrutor_idInstrutor`)
    REFERENCES `capacitacao`.`Instrutor` (`idInstrutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `capacitação`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capacitacao`.`Aluno` (
  `idAluno`	  INT(11) NOT NULL,
  `Nome` 	  VARCHAR(100) NOT NULL,
  `Cpf` 	  VARCHAR(15) NOT NULL,
  `DataNasc`  DATE NOT NULL,
  `Telefone`  CHAR(14) NOT NULL,
  `Email` 	  VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idAluno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `capacitação`.`Matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capacitacao`.`Matricula` (
  `idMatricula` 	INT(11) NOT NULL,
  `Data_Matricula` 	DATE NOT NULL,
  `Turma_idTurma` 	INT(11) NOT NULL,
  `Aluno_idAluno`   INT(11) NOT NULL,
  PRIMARY KEY (`idMatricula`),
 -- INDEX `fk_Matricula_Turma1_idx` (`Turma_idTurma` ASC) VISIBLE,
 -- INDEX `fk_Matricula_Aluno1_idx` (`Aluno_idAluno` ASC) VISIBLE,
  CONSTRAINT `fk_Matricula_Turma1`
    FOREIGN KEY (`Turma_idTurma`)
    REFERENCES `capacitacao`.`Turma` (`idTurma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Matricula_Aluno1`
    FOREIGN KEY (`Aluno_idAluno`)
    REFERENCES `capacitacao`.`Aluno` (`idAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
